import { Container, Flex, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import "./theme-config.css";
import AuthProvider from "./auth/AuthProvider";
import Footer from "@/Footer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} `}>
        <AuthProvider>
          <Theme accentColor="jade">
            <NavBar />
            <Flex direction="column" className="min-h-svh">
              <main className="p-6 flex-grow">
                <Container>{children}</Container>
              </main>
              <Footer />
            </Flex>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
